const locales = {
    'en': { loadingText: 'Loading...' },
    'bulgarian': { loadingText: 'Зареждане...' },
    'czech': { loadingText: 'Načítání...' },
    'danish': { loadingText: 'Indlæser...' },
    'dutch': { loadingText: 'Laden...' },
    'finnish': { loadingText: 'Ladataan...' },
    'french': { loadingText: 'Chargement...' },
    'german': { loadingText: 'Lädt...' },
    'greek': { loadingText: 'Φόρτωση...' },
    'hungarian': { loadingText: 'Töltés...' },
    'indonesian': { loadingText: 'Memuat...' },
    'italian': { loadingText: 'Caricamento...' },
    'japanese': { loadingText: '読み込み中...' },
    'koreana': { loadingText: '불러오는 중...' },
    'latam': { loadingText: 'Cargando...' },
    'norwegian': { loadingText: 'Laster inn...' },
    'polish': { loadingText: 'Wczytywanie...' },
    'portuguese': { loadingText: 'Carregando...' },
    'brazilian': { loadingText: 'Carregando...' },
    'romanian': { loadingText: 'Se încarcă...' },
    'russian': { loadingText: 'Загрузка...' },
    'schinese': { loadingText: '加载中...' },
    'spanish': { loadingText: 'Cargando...' },
    'swedish': { loadingText: 'Läser in...' },
    'tchinese': { loadingText: '載入中...' },
    'thai': { loadingText: 'กำลังโหลด...' },
    'turkish': { loadingText: 'Yükleniyor...' },
    'ukrainian': { loadingText: 'Завантаження...' },
    'vietnamese': { loadingText: 'Đang tải...' }
};