const locales = {
    'en': { 
        loadingText: 'Loading...',
        errorPostComment: 'Could not find comment box or post button.',
        errorParseConfig: 'Error parsing webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Display Options",
            highlightComments: "Highlight comments",
            showRepBar: "Show reputation bar",
            oldSchoolTheme: "Old-School Theme",
            countingLogic: "Counting Logic",
            countingMode: "Counting mode",
            countAll: "Count all comments",
            lastFromUser: "Last from user",
            majorityFromUser: "Majority from user",
            language: "Language",
            keywordManagement: "Keyword Management",
            editKeywords: "Edit Reputation Keywords",
            resetAllSettings: "Reset All Settings",
            editKeywordsTitle: "Edit Keywords",
            positiveKeywords: "Positive (+rep) Keywords",
            negativeKeywords: "Negative (-rep) Keywords",
            keywordsPlaceholder: "Enter words, separated by commas...",
            resetToDefault: "Reset to Default",
            cancel: "Cancel",
            save: "Save",
            confirmResetKeywords: "Are you sure you want to reset keywords to default?",
            confirmResetAll: "Are you sure you want to reset ALL settings? This cannot be undone."
        }
    },
    'russian': {
        loadingText: 'Загрузка...',
        errorPostComment: 'Не удалось найти поле для ввода комментария или кнопку отправки.',
        errorParseConfig: 'Ошибка парсинга webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Опции отображения",
            highlightComments: "Подсвечивать комментарии",
            showRepBar: "Показывать полосу репутации",
            oldSchoolTheme: "Олдскульная тема",
            countingLogic: "Логика подсчета",
            countingMode: "Режим подсчета",
            countAll: "Считать все комментарии",
            lastFromUser: "Только последний от пользователя",
            majorityFromUser: "По большинству от пользователя",
            language: "Язык",
            keywordManagement: "Управление ключевыми словами",
            editKeywords: "Редактировать ключевые слова",
            resetAllSettings: "Сбросить все настройки",
            editKeywordsTitle: "Редактировать слова",
            positiveKeywords: "Позитивные (+rep) слова",
            negativeKeywords: "Негативные (-rep) слова",
            keywordsPlaceholder: "Введите слова, разделяя их запятыми...",
            resetToDefault: "Сбросить",
            cancel: "Отмена",
            save: "Сохранить",
            confirmResetKeywords: "Вы уверены, что хотите сбросить ключевые слова до стандартных?",
            confirmResetAll: "Вы уверены, что хотите сбросить ВСЕ настройки? Это действие невозможно отменить."
        }
    },
    'ukrainian': {
        loadingText: 'Завантаження...',
        errorPostComment: 'Не вдалося знайти поле для коментаря або кнопку надсилання.',
        errorParseConfig: 'Помилка парсингу webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Опції відображення",
            highlightComments: "Підсвічувати коментарі",
            showRepBar: "Показувати смугу репутації",
            oldSchoolTheme: "Олдскульна тема",
            countingLogic: "Логіка підрахунку",
            countingMode: "Режим підрахунку",
            countAll: "Рахувати всі коментарі",
            lastFromUser: "Тільки останній від користувача",
            majorityFromUser: "За більшістю від користувача",
            language: "Мова",
            keywordManagement: "Керування ключовими словами",
            editKeywords: "Редагувати ключові слова",
            resetAllSettings: "Скинути всі налаштування",
            editKeywordsTitle: "Редагувати слова",
            positiveKeywords: "Позитивні (+rep) слова",
            negativeKeywords: "Негативні (-rep) слова",
            keywordsPlaceholder: "Введіть слова, розділяючи їх комами...",
            resetToDefault: "Скинути до стандартних",
            cancel: "Скасувати",
            save: "Зберегти",
            confirmResetKeywords: "Ви впевнені, що хочете скинути ключові слова до стандартних?",
            confirmResetAll: "Ви впевнені, що хочете скинути ВСІ налаштування? Цю дію неможливо скасувати."
        }
    },
    'bulgarian': {
        loadingText: 'Зареждане...',
        errorPostComment: 'Не може да се намери полето за коментари или бутонът за публикуване.',
        errorParseConfig: 'Грешка при анализа на webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Опции за показване",
            highlightComments: "Подчертаване на коментари",
            showRepBar: "Показване на лентата за репутация",
            oldSchoolTheme: "Тема в стар стил",
            countingLogic: "Логика на броене",
            countingMode: "Режим на броене",
            countAll: "Преброяване на всички коментари",
            lastFromUser: "Последен от потребител",
            majorityFromUser: "Според мнозинството от потребител",
            language: "Език",
            keywordManagement: "Управление на ключови думи",
            editKeywords: "Редактиране на ключови думи",
            resetAllSettings: "Нулиране на всички настройки",
            editKeywordsTitle: "Редактиране на думи",
            positiveKeywords: "Положителни (+rep) думи",
            negativeKeywords: "Отрицателни (-rep) думи",
            keywordsPlaceholder: "Въведете думи, разделени със запетаи...",
            resetToDefault: "Нулиране",
            cancel: "Отказ",
            save: "Запазване",
            confirmResetKeywords: "Сигурни ли сте, че искате да нулирате ключовите думи по подразбиране?",
            confirmResetAll: "Сигурни ли сте, че искате да нулирате ВСИЧКИ настройки? Това действие не може да бъде отменено."
        }
    },
    'czech': {
        loadingText: 'Načítání...',
        errorPostComment: 'Nepodařilo se najít pole pro komentář nebo tlačítko pro odeslání.',
        errorParseConfig: 'Chyba při parsování webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Možnosti zobrazení",
            highlightComments: "Zvýraznit komentáře",
            showRepBar: "Zobrazit lištu reputace",
            oldSchoolTheme: "Old-School téma",
            countingLogic: "Logika počítání",
            countingMode: "Režim počítání",
            countAll: "Počítat všechny komentáře",
            lastFromUser: "Poslední od uživatele",
            majorityFromUser: "Většina od uživatele",
            language: "Jazyk",
            keywordManagement: "Správa klíčových slov",
            editKeywords: "Upravit klíčová slova",
            resetAllSettings: "Obnovit všechna nastavení",
            editKeywordsTitle: "Upravit slova",
            positiveKeywords: "Pozitivní (+rep) klíčová slova",
            negativeKeywords: "Negativní (-rep) klíčová slova",
            keywordsPlaceholder: "Zadejte slova oddělená čárkami...",
            resetToDefault: "Obnovit výchozí",
            cancel: "Zrušit",
            save: "Uložit",
            confirmResetKeywords: "Jste si jisti, že chcete obnovit klíčová slova na výchozí?",
            confirmResetAll: "Jste si jisti, že chcete obnovit VŠECHNA nastavení? Tuto akci nelze vrátit."
        }
    },
    'danish': {
        loadingText: 'Indlæser...',
        errorPostComment: 'Kunne ikke finde kommentarfelt eller publiceringsknap.',
        errorParseConfig: 'Fejl ved fortolkning af webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Visningsmuligheder",
            highlightComments: "Fremhæv kommentarer",
            showRepBar: "Vis omdømmebjælke",
            oldSchoolTheme: "Old-School Tema",
            countingLogic: "Tællingslogik",
            countingMode: "Tælletilstand",
            countAll: "Tæl alle kommentarer",
            lastFromUser: "Sidste fra bruger",
            majorityFromUser: "Flertal fra bruger",
            language: "Sprog",
            keywordManagement: "Administration af nøgleord",
            editKeywords: "Rediger omdømme-nøgleord",
            resetAllSettings: "Nulstil alle indstillinger",
            editKeywordsTitle: "Rediger nøgleord",
            positiveKeywords: "Positive (+rep) nøgleord",
            negativeKeywords: "Negative (-rep) nøgleord",
            keywordsPlaceholder: "Indtast ord, adskilt af kommaer...",
            resetToDefault: "Nulstil",
            cancel: "Annuller",
            save: "Gem",
            confirmResetKeywords: "Er du sikker på, at du vil nulstille nøgleord til standard?",
            confirmResetAll: "Er du sikker på, at du vil nulstille ALLE indstillinger? Dette kan ikke fortrydes."
        }
    },
    'dutch': {
        loadingText: 'Laden...',
        errorPostComment: 'Kon het opmerkingenveld of de postknop niet vinden.',
        errorParseConfig: 'Fout bij het parsen van webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Weergaveopties",
            highlightComments: "Reacties markeren",
            showRepBar: "Reputatiebalk tonen",
            oldSchoolTheme: "Old-School Thema",
            countingLogic: "Tellogica",
            countingMode: "Telmodus",
            countAll: "Alle reacties tellen",
            lastFromUser: "Laatste van gebruiker",
            majorityFromUser: "Meerderheid van gebruiker",
            language: "Taal",
            keywordManagement: "Sleutelwoordenbeheer",
            editKeywords: "Reputatie-sleutelwoorden bewerken",
            resetAllSettings: "Alle instellingen resetten",
            editKeywordsTitle: "Sleutelwoorden bewerken",
            positiveKeywords: "Positieve (+rep) sleutelwoorden",
            negativeKeywords: "Negatieve (-rep) sleutelwoorden",
            keywordsPlaceholder: "Voer woorden in, gescheiden door komma's...",
            resetToDefault: "Reset naar standaard",
            cancel: "Annuleren",
            save: "Opslaan",
            confirmResetKeywords: "Weet u zeker dat u de sleutelwoorden naar de standaard wilt resetten?",
            confirmResetAll: "Weet u zeker dat u ALLE instellingen wilt resetten? Dit kan niet ongedaan worden gemaakt."
        }
    },
    'finnish': {
        loadingText: 'Ladataan...',
        errorPostComment: 'Kommenttikenttää tai lähetyspainiketta ei löytynyt.',
        errorParseConfig: 'Virhe jäsennettäessä webui_config-tiedostoa',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Näyttöasetukset",
            highlightComments: "Korosta kommentit",
            showRepBar: "Näytä mainepalkki",
            oldSchoolTheme: "Vanhan koulun teema",
            countingLogic: "Laskentalogiikka",
            countingMode: "Laskentatila",
            countAll: "Laske kaikki kommentit",
            lastFromUser: "Viimeisin käyttäjältä",
            majorityFromUser: "Enemmistö käyttäjältä",
            language: "Kieli",
            keywordManagement: "Avainsanojen hallinta",
            editKeywords: "Muokkaa mainesanoja",
            resetAllSettings: "Nollaa kaikki asetukset",
            editKeywordsTitle: "Muokkaa avainsanoja",
            positiveKeywords: "Positiiviset (+rep) avainsanat",
            negativeKeywords: "Negatiiviset (-rep) avainsanat",
            keywordsPlaceholder: "Syötä sanat pilkuilla erotettuna...",
            resetToDefault: "Palauta oletukset",
            cancel: "Peruuta",
            save: "Tallenna",
            confirmResetKeywords: "Haluatko varmasti palauttaa avainsanat oletusasetuksiin?",
            confirmResetAll: "Haluatko varmasti nollata KAIKKI asetukset? Toimintoa ei voi kumota."
        }
    },
    'french': {
        loadingText: 'Chargement...',
        errorPostComment: 'Impossible de trouver la zone de commentaire ou le bouton de publication.',
        errorParseConfig: 'Erreur d\'analyse de webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Options d'affichage",
            highlightComments: "Surligner les commentaires",
            showRepBar: "Afficher la barre de réputation",
            oldSchoolTheme: "Thème Old-School",
            countingLogic: "Logique de comptage",
            countingMode: "Mode de comptage",
            countAll: "Compter tous les commentaires",
            lastFromUser: "Dernier par utilisateur",
            majorityFromUser: "Majorité par utilisateur",
            language: "Langue",
            keywordManagement: "Gestion des mots-clés",
            editKeywords: "Modifier les mots-clés de réputation",
            resetAllSettings: "Réinitialiser tous les paramètres",
            editKeywordsTitle: "Modifier les mots-clés",
            positiveKeywords: "Mots-clés positifs (+rep)",
            negativeKeywords: "Mots-clés négatifs (-rep)",
            keywordsPlaceholder: "Entrez les mots, séparés par des virgules...",
            resetToDefault: "Réinitialiser",
            cancel: "Annuler",
            save: "Enregistrer",
            confirmResetKeywords: "Voulez-vous vraiment réinitialiser les mots-clés par défaut?",
            confirmResetAll: "Voulez-vous vraiment réinitialiser TOUS les paramètres? Cette action est irréversible."
        }
    },
    'german': {
        loadingText: 'Lädt...',
        errorPostComment: 'Kommentarfeld oder Senden-Button nicht gefunden.',
        errorParseConfig: 'Fehler beim Parsen von webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Anzeigeoptionen",
            highlightComments: "Kommentare hervorheben",
            showRepBar: "Reputationsleiste anzeigen",
            oldSchoolTheme: "Old-School-Design",
            countingLogic: "Zähllogik",
            countingMode: "Zählmodus",
            countAll: "Alle Kommentare zählen",
            lastFromUser: "Letzter pro Benutzer",
            majorityFromUser: "Mehrheit pro Benutzer",
            language: "Sprache",
            keywordManagement: "Schlüsselwort-Verwaltung",
            editKeywords: "Reputations-Schlüsselwörter bearbeiten",
            resetAllSettings: "Alle Einstellungen zurücksetzen",
            editKeywordsTitle: "Schlüsselwörter bearbeiten",
            positiveKeywords: "Positive (+rep) Schlüsselwörter",
            negativeKeywords: "Negative (-rep) Schlüsselwörter",
            keywordsPlaceholder: "Wörter eingeben, durch Kommas getrennt...",
            resetToDefault: "Zurücksetzen",
            cancel: "Abbrechen",
            save: "Speichern",
            confirmResetKeywords: "Möchten Sie die Schlüsselwörter wirklich auf den Standard zurücksetzen?",
            confirmResetAll: "Möchten Sie wirklich ALLE Einstellungen zurücksetzen? Dies kann nicht rückgängig gemacht werden."
        }
    },
    'greek': {
        loadingText: 'Φόρτωση...',
        errorPostComment: 'Δεν ήταν δυνατή η εύρεση του πλαισίου σχολίων ή του κουμπιού δημοσίευσης.',
        errorParseConfig: 'Σφάλμα ανάλυσης του webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Επιλογές εμφάνισης",
            highlightComments: "Επισήμανση σχολίων",
            showRepBar: "Εμφάνιση μπάρας φήμης",
            oldSchoolTheme: "Old-School Θέμα",
            countingLogic: "Λογική καταμέτρησης",
            countingMode: "Τρόπος καταμέτρησης",
            countAll: "Καταμέτρηση όλων των σχολίων",
            lastFromUser: "Τελευταίο από χρήστη",
            majorityFromUser: "Πλειοψηφία από χρήστη",
            language: "Γλώσσα",
            keywordManagement: "Διαχείριση λέξεων-κλειδιών",
            editKeywords: "Επεξεργασία λέξεων-κλειδιών",
            resetAllSettings: "Επαναφορά όλων των ρυθμίσεων",
            editKeywordsTitle: "Επεξεργασία λέξεων-κλειδιών",
            positiveKeywords: "Θετικές (+rep) λέξεις-κλειδιά",
            negativeKeywords: "Αρνητικές (-rep) λέξεις-κλειδιά",
            keywordsPlaceholder: "Εισαγάγετε λέξεις, χωρισμένες με κόμμα...",
            resetToDefault: "Επαναφορά",
            cancel: "Άκυρο",
            save: "Αποθήκευση",
            confirmResetKeywords: "Είστε βέβαιοι ότι θέλεте να επαναφέρετε τις λέξεις-κλειδιά στις προεπιλογές;",
            confirmResetAll: "Είστε βέβαιοι ότι θέλεте να επαναφέρετε ΟΛΕΣ τις ρυθμίσεις; Αυτή η ενέργεια δεν μπορεί να αναιρεθεί."
        }
    },
    'hungarian': {
        loadingText: 'Töltés...',
        errorPostComment: 'A kommentmező vagy a közzététel gomb nem található.',
        errorParseConfig: 'Hiba a webui_config elemzésekor',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Megjelenítési opciók",
            highlightComments: "Hozzászólások kiemelése",
            showRepBar: "Reputációsáv mutatása",
            oldSchoolTheme: "Old-School téma",
            countingLogic: "Számlálási logika",
            countingMode: "Számlálási mód",
            countAll: "Összes hozzászólás számolása",
            lastFromUser: "Utolsó a felhasználótól",
            majorityFromUser: "Többség a felhasználótól",
            language: "Nyelv",
            keywordManagement: "Kulcsszavak kezelése",
            editKeywords: "Hírnév kulcsszavak szerkesztése",
            resetAllSettings: "Minden beállítás visszaállítása",
            editKeywordsTitle: "Kulcsszavak szerkesztése",
            positiveKeywords: "Pozitív (+rep) kulcsszavak",
            negativeKeywords: "Negatív (-rep) kulcsszavak",
            keywordsPlaceholder: "Írja be a szavakat, vesszővel elválasztva...",
            resetToDefault: "Visszaállítás",
            cancel: "Mégse",
            save: "Mentés",
            confirmResetKeywords: "Biztosan visszaállítja a kulcsszavakat az alapértelmezettre?",
            confirmResetAll: "Biztosan visszaállítja AZ ÖSSZES beállítást? Ez a művelet nem vonható vissza."
        }
    },
    'indonesian': {
        loadingText: 'Memuat...',
        errorPostComment: 'Tidak dapat menemukan kotak komentar atau tombol kirim.',
        errorParseConfig: 'Gagal mem-parsing webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Opsi Tampilan",
            highlightComments: "Sorot komentar",
            showRepBar: "Tampilkan bar reputasi",
            oldSchoolTheme: "Tema Jadul",
            countingLogic: "Logika Penghitungan",
            countingMode: "Mode penghitungan",
            countAll: "Hitung semua komentar",
            lastFromUser: "Terakhir dari pengguna",
            majorityFromUser: "Mayoritas dari pengguna",
            language: "Bahasa",
            keywordManagement: "Manajemen Kata Kunci",
            editKeywords: "Edit Kata Kunci Reputasi",
            resetAllSettings: "Reset Semua Pengaturan",
            editKeywordsTitle: "Edit Kata Kunci",
            positiveKeywords: "Kata Kunci Positif (+rep)",
            negativeKeywords: "Kata Kunci Negatif (-rep)",
            keywordsPlaceholder: "Masukkan kata, dipisahkan oleh koma...",
            resetToDefault: "Reset ke Default",
            cancel: "Batal",
            save: "Simpan",
            confirmResetKeywords: "Anda yakin ingin mereset kata kunci ke default?",
            confirmResetAll: "Anda yakin ingin mereset SEMUA pengaturan? Tindakan ini tidak dapat dibatalkan."
        }
    },
    'italian': {
        loadingText: 'Caricamento...',
        errorPostComment: 'Impossibile trovare la casella dei commenti o il pulsante di pubblicazione.',
        errorParseConfig: 'Errore durante il parsing di webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Opzioni di visualizzazione",
            highlightComments: "Evidenzia commenti",
            showRepBar: "Mostra barra reputazione",
            oldSchoolTheme: "Tema Old-School",
            countingLogic: "Logica di conteggio",
            countingMode: "Modalità di conteggio",
            countAll: "Conta tutti i commenti",
            lastFromUser: "Ultimo dall'utente",
            majorityFromUser: "Maggioranza dall'utente",
            language: "Lingua",
            keywordManagement: "Gestione parole chiave",
            editKeywords: "Modifica parole chiave reputazione",
            resetAllSettings: "Ripristina tutte le impostazioni",
            editKeywordsTitle: "Modifica parole chiave",
            positiveKeywords: "Parole chiave positive (+rep)",
            negativeKeywords: "Parole chiave negative (-rep)",
            keywordsPlaceholder: "Inserisci parole, separate da virgole...",
            resetToDefault: "Ripristina",
            cancel: "Annulla",
            save: "Salva",
            confirmResetKeywords: "Sei sicuro di voler ripristinare le parole chiave predefinite?",
            confirmResetAll: "Sei sicuro di voler ripristinare TUTTE le impostazioni? L'azione non può essere annullata."
        }
    },
    'japanese': {
        loadingText: '読み込み中...',
        errorPostComment: 'コメントボックスまたは投稿ボタンが見つかりませんでした。',
        errorParseConfig: 'webui_config の解析中にエラーが発生しました',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "表示オプション",
            highlightComments: "コメントをハイライト",
            showRepBar: "評価バーを表示",
            oldSchoolTheme: "オールドスクールテーマ",
            countingLogic: "カウントロジック",
            countingMode: "カウントモード",
            countAll: "すべてのコメントをカウント",
            lastFromUser: "ユーザーごとに最新のみ",
            majorityFromUser: "ユーザーごとに多数決",
            language: "言語",
            keywordManagement: "キーワード管理",
            editKeywords: "評価キーワードを編集",
            resetAllSettings: "すべての設定をリセット",
            editKeywordsTitle: "キーワードを編集",
            positiveKeywords: "ポジティブ (+rep) キーワード",
            negativeKeywords: "ネガティブ (-rep) キーワード",
            keywordsPlaceholder: "単語をコンマ区切りで入力...",
            resetToDefault: "リセット",
            cancel: "キャンセル",
            save: "保存",
            confirmResetKeywords: "キーワードをデフォルトにリセットしてもよろしいですか？",
            confirmResetAll: "すべての設定をリセットしてもよろしいですか？この操作は元に戻せません。"
        }
    },
    'koreana': {
        loadingText: '불러오는 중...',
        errorPostComment: '댓글 상자 또는 게시 버튼을 찾을 수 없습니다.',
        errorParseConfig: 'webui_config를 파싱하는 중 오류가 발생했습니다',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "표시 옵션",
            highlightComments: "댓글 강조 표시",
            showRepBar: "평판 바 표시",
            oldSchoolTheme: "올드스쿨 테마",
            countingLogic: "계산 로직",
            countingMode: "계산 모드",
            countAll: "모든 댓글 계산",
            lastFromUser: "사용자별 마지막 댓글",
            majorityFromUser: "사용자별 과반수",
            language: "언어",
            keywordManagement: "키워드 관리",
            editKeywords: "평판 키워드 편집",
            resetAllSettings: "모든 설정 초기화",
            editKeywordsTitle: "키워드 편집",
            positiveKeywords: "긍정적 (+rep) 키워드",
            negativeKeywords: "부정적 (-rep) 키워드",
            keywordsPlaceholder: "단어를 쉼표로 구분하여 입력...",
            resetToDefault: "기본값으로 재설정",
            cancel: "취소",
            save: "저장",
            confirmResetKeywords: "키워드를 기본값으로 재설정하시겠습니까?",
            confirmResetAll: "모든 설정을 초기화하시겠습니까? 이 작업은 되돌릴 수 없습니다."
        }
    },
    'latam': {
        loadingText: 'Cargando...',
        errorPostComment: 'No se pudo encontrar el cuadro de comentarios o el botón de publicar.',
        errorParseConfig: 'Error al analizar webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Opciones de visualización",
            highlightComments: "Resaltar comentarios",
            showRepBar: "Mostrar barra de reputación",
            oldSchoolTheme: "Tema Clásico",
            countingLogic: "Lógica de recuento",
            countingMode: "Modo de recuento",
            countAll: "Contar todos los comentarios",
            lastFromUser: "Último por usuario",
            majorityFromUser: "Mayoría por usuario",
            language: "Idioma",
            keywordManagement: "Gestión de palabras clave",
            editKeywords: "Editar palabras clave de reputación",
            resetAllSettings: "Restablecer todos los ajustes",
            editKeywordsTitle: "Editar palabras clave",
            positiveKeywords: "Palabras clave positivas (+rep)",
            negativeKeywords: "Palabras clave negativas (-rep)",
            keywordsPlaceholder: "Introduce palabras, separadas por comas...",
            resetToDefault: "Restablecer",
            cancel: "Cancelar",
            save: "Guardar",
            confirmResetKeywords: "¿Estás seguro de que quieres restablecer las palabras clave a sus valores predeterminados?",
            confirmResetAll: "¿Estás seguro de que quieres restablecer TODOS los ajustes? Esta acción no se puede deshacer."
        }
    },
    'norwegian': {
        loadingText: 'Laster inn...',
        errorPostComment: 'Kunne ikke finne kommentarfeltet eller publiseringsknappen.',
        errorParseConfig: 'Feil ved parsing av webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Visningsalternativer",
            highlightComments: "Uthev kommentarer",
            showRepBar: "Vis omdømme-linje",
            oldSchoolTheme: "Old-School Tema",
            countingLogic: " tellelogikk",
            countingMode: "Tellemodus",
            countAll: "Tell alle kommentarer",
            lastFromUser: "Siste fra bruker",
            majorityFromUser: "Majoritet fra bruker",
            language: "Språk",
            keywordManagement: "Nøkkelordbehandling",
            editKeywords: "Rediger omdømme-nøkkelord",
            resetAllSettings: "Tilbakestill alle innstillinger",
            editKeywordsTitle: "Rediger nøkkelord",
            positiveKeywords: "Positive (+rep) nøkkelord",
            negativeKeywords: "Negative (-rep) nøkkelord",
            keywordsPlaceholder: "Skriv inn ord, atskilt med komma...",
            resetToDefault: "Tilbakestill",
            cancel: "Avbryt",
            save: "Lagre",
            confirmResetKeywords: "Er du sikker på at du vil tilbakestille nøkkelord til standard?",
            confirmResetAll: "Er du sikker på at du vil tilbakestille ALLE innstillinger? Dette kan ikke angres."
        }
    },
    'polish': {
        loadingText: 'Wczytywanie...',
        errorPostComment: 'Nie można znaleźć pola komentarza lub przycisku publikacji.',
        errorParseConfig: 'Błąd podczas parsowania webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Opcje wyświetlania",
            highlightComments: "Podświetlaj komentarze",
            showRepBar: "Pokaż pasek reputacji",
            oldSchoolTheme: "Motyw Old-School",
            countingLogic: "Logika liczenia",
            countingMode: "Tryb liczenia",
            countAll: "Licz wszystkie komentarze",
            lastFromUser: "Ostatni od użytkownika",
            majorityFromUser: "Większość od użytkownika",
            language: "Język",
            keywordManagement: "Zarządzanie słowami kluczowymi",
            editKeywords: "Edytuj słowa kluczowe reputacji",
            resetAllSettings: "Zresetuj wszystkie ustawienia",
            editKeywordsTitle: "Edytuj słowa kluczowe",
            positiveKeywords: "Pozytywne (+rep) słowa kluczowe",
            negativeKeywords: "Negatywne (-rep) słowa kluczowe",
            keywordsPlaceholder: "Wprowadź słowa, oddzielając je przecinkami...",
            resetToDefault: "Resetuj",
            cancel: "Anuluj",
            save: "Zapisz",
            confirmResetKeywords: "Czy na pewno chcesz zresetować słowa kluczowe do domyślnych?",
            confirmResetAll: "Czy na pewno chcesz zresetować WSZYSTKIE ustawienia? Tej operacji nie można cofnąć."
        }
    },
    'portuguese': {
        loadingText: 'Carregando...',
        errorPostComment: 'Não foi possível encontrar a caixa de comentários ou o botão de postar.',
        errorParseConfig: 'Erro ao analisar webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Opções de Exibição",
            highlightComments: "Destacar comentários",
            showRepBar: "Mostrar barra de reputação",
            oldSchoolTheme: "Tema Clássico",
            countingLogic: "Lógica de Contagem",
            countingMode: "Modo de contagem",
            countAll: "Contar todos os comentários",
            lastFromUser: "Último do utilizador",
            majorityFromUser: "Maioria do utilizador",
            language: "Idioma",
            keywordManagement: "Gestão de palavras-chave",
            editKeywords: "Editar palavras-chave de reputação",
            resetAllSettings: "Repor todas as configurações",
            editKeywordsTitle: "Editar palavras-chave",
            positiveKeywords: "Palavras-chave positivas (+rep)",
            negativeKeywords: "Palavras-chave negativas (-rep)",
            keywordsPlaceholder: "Introduza palavras, separadas por vírgulas...",
            resetToDefault: "Repor padrão",
            cancel: "Cancelar",
            save: "Guardar",
            confirmResetKeywords: "Tem a certeza de que quer repor as palavras-chave para as predefinições?",
            confirmResetAll: "Tem a certeza de que quer repor TODAS as configurações? Esta ação não pode ser desfeita."
        }
    },
    'brazilian': {
        loadingText: 'Carregando...',
        errorPostComment: 'Não foi possível encontrar a caixa de comentários ou o botão de postar.',
        errorParseConfig: 'Erro ao analisar webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Opções de Exibição",
            highlightComments: "Destacar comentários",
            showRepBar: "Exibir barra de reputação",
            oldSchoolTheme: "Tema Old-School",
            countingLogic: "Lógica de Contagem",
            countingMode: "Modo de contagem",
            countAll: "Contar todos os comentários",
            lastFromUser: "Último do usuário",
            majorityFromUser: "Maioria do usuário",
            language: "Idioma",
            keywordManagement: "Gerenciamento de palavras-chave",
            editKeywords: "Editar palavras-chave de reputação",
            resetAllSettings: "Redefinir todas as configurações",
            editKeywordsTitle: "Editar palavras-chave",
            positiveKeywords: "Palavras-chave positivas (+rep)",
            negativeKeywords: "Palavras-chave negativas (-rep)",
            keywordsPlaceholder: "Digite as palavras, separadas por vírgulas...",
            resetToDefault: "Redefinir padrão",
            cancel: "Cancelar",
            save: "Salvar",
            confirmResetKeywords: "Tem certeza de que deseja redefinir as palavras-chave para o padrão?",
            confirmResetAll: "Tem certeza de que deseja redefinir TODAS as configurações? Esta ação não pode ser desfeita."
        }
    },
    'romanian': {
        loadingText: 'Se încarcă...',
        errorPostComment: 'Nu s-a găsit caseta de comentarii sau butonul de postare.',
        errorParseConfig: 'Eroare la parsarea webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Opțiuni de afișare",
            highlightComments: "Evidențiază comentariile",
            showRepBar: "Arată bara de reputație",
            oldSchoolTheme: "Temă Old-School",
            countingLogic: "Logica de numărare",
            countingMode: "Mod de numărare",
            countAll: "Numără toate comentariile",
            lastFromUser: "Ultimul de la utilizator",
            majorityFromUser: "Majoritatea de la utilizator",
            language: "Limbă",
            keywordManagement: "Gestionarea cuvintelor cheie",
            editKeywords: "Editați cuvintele cheie pentru reputație",
            resetAllSettings: "Resetează toate setările",
            editKeywordsTitle: "Editați cuvintele cheie",
            positiveKeywords: "Cuvinte cheie pozitive (+rep)",
            negativeKeywords: "Cuvinte cheie negative (-rep)",
            keywordsPlaceholder: "Introduceți cuvinte, separate prin virgulă...",
            resetToDefault: "Revenire la implicit",
            cancel: "Anulare",
            save: "Salvare",
            confirmResetKeywords: "Sunteți sigur că doriți să resetați cuvintele cheie la valorile implicite?",
            confirmResetAll: "Sunteți sigur că doriți să resetați TOATE setările? Această acțiune nu poate fi anulată."
        }
    },
    'schinese': {
        loadingText: '加载中...',
        errorPostComment: '未能找到评论框或发布按钮。',
        errorParseConfig: '解析 webui_config 时出错',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "显示选项",
            highlightComments: "高亮评论",
            showRepBar: "显示声誉条",
            oldSchoolTheme: "复古主题",
            countingLogic: "计数逻辑",
            countingMode: "计数模式",
            countAll: "计算所有评论",
            lastFromUser: "来自用户的最后一条",
            majorityFromUser: "来自用户的多数",
            language: "语言",
            keywordManagement: "关键词管理",
            editKeywords: "编辑声誉关键词",
            resetAllSettings: "重置所有设置",
            editKeywordsTitle: "编辑关键词",
            positiveKeywords: "正面 (+rep) 关键词",
            negativeKeywords: "负面 (-rep) 关键词",
            keywordsPlaceholder: "输入词语，用逗号分隔...",
            resetToDefault: "重置为默认",
            cancel: "取消",
            save: "保存",
            confirmResetKeywords: "您确定要将关键词重置为默认值吗？",
            confirmResetAll: "您确定要重置所有设置吗？此操作无法撤销。"
        }
    },
    'spanish': {
        loadingText: 'Cargando...',
        errorPostComment: 'No se pudo encontrar el cuadro de comentarios o el botón de publicar.',
        errorParseConfig: 'Error al analizar webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Opciones de visualización",
            highlightComments: "Resaltar comentarios",
            showRepBar: "Mostrar barra de reputación",
            oldSchoolTheme: "Tema Clásico",
            countingLogic: "Lógica de recuento",
            countingMode: "Modo de recuento",
            countAll: "Contar todos los comentarios",
            lastFromUser: "Último por usuario",
            majorityFromUser: "Mayoría por usuario",
            language: "Idioma",
            keywordManagement: "Gestión de palabras clave",
            editKeywords: "Editar palabras clave de reputación",
            resetAllSettings: "Restablecer todos los ajustes",
            editKeywordsTitle: "Editar palabras clave",
            positiveKeywords: "Palabras clave positivas (+rep)",
            negativeKeywords: "Palabras clave negativas (-rep)",
            keywordsPlaceholder: "Introduce palabras, separadas por comas...",
            resetToDefault: "Restablecer",
            cancel: "Cancelar",
            save: "Guardar",
            confirmResetKeywords: "¿Estás seguro de que quieres restablecer las palabras clave a sus valores predeterminados?",
            confirmResetAll: "¿Estás seguro de que quieres restablecer TODOS los ajustes? Esta acción no se puede deshacer."
        }
    },
    'swedish': {
        loadingText: 'Läser in...',
        errorPostComment: 'Kunde inte hitta kommentarsfältet eller publiceringsknappen.',
        errorParseConfig: 'Fel vid tolkning av webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Visningsalternativ",
            highlightComments: "Markera kommentarer",
            showRepBar: "Visa ryktesfält",
            oldSchoolTheme: "Gammaldags tema",
            countingLogic: "Räkningslogik",
            countingMode: "Räkningsläge",
            countAll: "Räkna alla kommentarer",
            lastFromUser: "Senaste från användare",
            majorityFromUser: "Majoritet från användare",
            language: "Språk",
            keywordManagement: "Nyckelordshantering",
            editKeywords: "Redigera ryktesnyckelord",
            resetAllSettings: "Återställ alla inställningar",
            editKeywordsTitle: "Redigera nyckelord",
            positiveKeywords: "Positiva (+rep) nyckelord",
            negativeKeywords: "Negativa (-rep) nyckelord",
            keywordsPlaceholder: "Ange ord, separerade med kommatecken...",
            resetToDefault: "Återställ",
            cancel: "Avbryt",
            save: "Spara",
            confirmResetKeywords: "Är du säker på att du vill återställa nyckelorden till standard?",
            confirmResetAll: "Är du säker på att du vill återställa ALLA inställningar? Detta kan inte ångras."
        }
    },
    'tchinese': {
        loadingText: '載入中...',
        errorPostComment: '未能找到評論框或發布按鈕。',
        errorParseConfig: '解析 webui_config 時出錯',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "顯示選項",
            highlightComments: "高亮評論",
            showRepBar: "顯示聲譽條",
            oldSchoolTheme: "復古主題",
            countingLogic: "計數邏輯",
            countingMode: "計數模式",
            countAll: "計算所有評論",
            lastFromUser: "來自使用者的最後一條",
            majorityFromUser: "來自使用者的多數",
            language: "語言",
            keywordManagement: "關鍵詞管理",
            editKeywords: "編輯聲譽關鍵詞",
            resetAllSettings: "重設所有設定",
            editKeywordsTitle: "編輯關鍵詞",
            positiveKeywords: "正面 (+rep) 關鍵詞",
            negativeKeywords: "負面 (-rep) 關鍵詞",
            keywordsPlaceholder: "輸入詞語，用逗號分隔...",
            resetToDefault: "重設為預設值",
            cancel: "取消",
            save: "儲存",
            confirmResetKeywords: "您確定要將關鍵詞重設為預設值嗎？",
            confirmResetAll: "您確定要重設所有設定嗎？此操作無法復原。"
        }
    },
    'thai': {
        loadingText: 'กำลังโหลด...',
        errorPostComment: 'ไม่พบกล่องแสดงความคิดเห็นหรือปุ่มโพสต์',
        errorParseConfig: 'เกิดข้อผิดพลาดในการแยกวิเคราะห์ webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "ตัวเลือกการแสดงผล",
            highlightComments: "ไฮไลท์ความคิดเห็น",
            showRepBar: "แสดงแถบชื่อเสียง",
            oldSchoolTheme: "ธีมแบบเก่า",
            countingLogic: "ตรรกะการนับ",
            countingMode: "โหมดการนับ",
            countAll: "นับความคิดเห็นทั้งหมด",
            lastFromUser: "ล่าสุดจากผู้ใช้",
            majorityFromUser: "ส่วนใหญ่จากผู้ใช้",
            language: "ภาษา",
            keywordManagement: "การจัดการคีย์เวิร์ด",
            editKeywords: "แก้ไขคีย์เวิร์ดชื่อเสียง",
            resetAllSettings: "รีเซ็ตการตั้งค่าทั้งหมด",
            editKeywordsTitle: "แก้ไขคีย์เวิร์ด",
            positiveKeywords: "คีย์เวิร์ดเชิงบวก (+rep)",
            negativeKeywords: "คีย์เวิร์ดเชิงลบ (-rep)",
            keywordsPlaceholder: "ป้อนคำโดยคั่นด้วยเครื่องหมายจุลภาค...",
            resetToDefault: "รีเซ็ต",
            cancel: "ยกเลิก",
            save: "บันทึก",
            confirmResetKeywords: "คุณแน่ใจหรือไม่ว่าต้องการรีเซ็ตคีย์เวิร์ดเป็นค่าเริ่มต้น",
            confirmResetAll: "คุณแน่ใจหรือไม่ว่าต้องการรีเซ็ตการตั้งค่าทั้งหมด? การกระทำนี้ไม่สามารถยกเลิกได้"
        }
    },
    'turkish': {
        loadingText: 'Yükleniyor...',
        errorPostComment: 'Yorum kutusu veya gönderme düğmesi bulunamadı.',
        errorParseConfig: 'webui_config ayrıştırılırken hata oluştu',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Görünüm Seçenekleri",
            highlightComments: "Yorumları vurgula",
            showRepBar: "İtibar çubuğunu göster",
            oldSchoolTheme: "Eski Tarz Tema",
            countingLogic: "Sayımlama Mantığı",
            countingMode: "Sayımlama modu",
            countAll: "Tüm yorumları say",
            lastFromUser: "Kullanıcıdan sonuncusu",
            majorityFromUser: "Kullanıcıdan çoğunluk",
            language: "Dil",
            keywordManagement: "Anahtar Kelime Yönetimi",
            editKeywords: "İtibar Anahtar Kelimelerini Düzenle",
            resetAllSettings: "Tüm Ayarları Sıfırla",
            editKeywordsTitle: "Kelimeleri Düzenle",
            positiveKeywords: "Pozitif (+rep) Kelimeler",
            negativeKeywords: "Negatif (-rep) Kelimeler",
            keywordsPlaceholder: "Kelimeleri virgülle ayırarak girin...",
            resetToDefault: "Sıfırla",
            cancel: "İptal",
            save: "Kaydet",
            confirmResetKeywords: "Anahtar kelimeleri varsayılana sıfırlamak istediğinizden emin misiniz?",
            confirmResetAll: "Tüm ayarları sıfırlamak istediğinizden emin misiniz? Bu işlem geri alınamaz."
        }
    },
    'vietnamese': {
        loadingText: 'Đang tải...',
        errorPostComment: 'Không tìm thấy hộp bình luận hoặc nút đăng.',
        errorParseConfig: 'Lỗi phân tích cú pháp webui_config',
        settingsUI: {
            title: "SteamRepCounter",
            displayOptions: "Tùy chọn hiển thị",
            highlightComments: "Làm nổi bật bình luận",
            showRepBar: "Hiển thị thanh uy tín",
            oldSchoolTheme: "Chủ đề Cổ điển",
            countingLogic: "Logic đếm",
            countingMode: "Chế độ đếm",
            countAll: "Đếm tất cả bình luận",
            lastFromUser: "Cuối cùng từ người dùng",
            majorityFromUser: "Đa số từ người dùng",
            language: "Ngôn ngữ",
            keywordManagement: "Quản lý từ khóa",
            editKeywords: "Chỉnh sửa từ khóa uy tín",
            resetAllSettings: "Đặt lại tất cả cài đặt",
            editKeywordsTitle: "Chỉnh sửa từ khóa",
            positiveKeywords: "Từ khóa tích cực (+rep)",
            negativeKeywords: "Từ khóa tiêu cực (-rep)",
            keywordsPlaceholder: "Nhập các từ, cách nhau bằng dấu phẩy...",
            resetToDefault: "Đặt lại",
            cancel: "Hủy",
            save: "Lưu",
            confirmResetKeywords: "Bạn có chắc chắn muốn đặt lại từ khóa về mặc định không?",
            confirmResetAll: "Bạn có chắc chắn muốn đặt lại TẤT CẢ cài đặt không? Hành động này không thể hoàn tác."
        }
    }
};